# -*- coding: utf-8 -*-
"""STT_whisper_deneme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-57mKJjbmOMTOB6GvnAMov8-gsP8Rz6x

**STT**-**whisper**
"""

!pip install --upgrade --no-cache-dir openai-whisper
!apt-get update && apt-get install -y ffmpeg

from google.colab import files
files = files.upload()

import whisper
import os

def transcribe_folder(folder_path, prefix, model_name="large"):
    model = whisper.load_model(model_name)
    output_file = f"{prefix}_transcriptions.txt"
    with open(output_file, "w", encoding="utf-8") as out:
        for filename in os.listdir(folder_path):
            if filename.endswith(".wav"):
                file_path = os.path.join(folder_path, filename)
                print(f"Processing: {file_path}")
                result = model.transcribe(file_path, language="tr")
                out.write(f"{filename}: {result['text']}\n\n")
                print(f"Transcribed: {filename}")
    print(f"All transcriptions saved to {output_file}")
    return output_file

agent_output, user_count = transcribe_folder("user", "user")

### whisper kendi sesimle deneme
import whisper

model = whisper.load_model("large")

result = model.transcribe("kayit.m4a", language="tr")
print("Çözümlenen metin:", result["text"])
