# -*- coding: utf-8 -*-
"""xtts_v2_deneme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCi3fbXFghm5EJqylftwPGk1GK4UNiFD
"""

from google.colab import files
uploaded = files.upload()

!pip install transformers==4.39.3
!pip install --upgrade TTS torch

import torch
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import XttsAudioConfig, XttsArgs
from TTS.config.shared_configs import BaseDatasetConfig
import torch.serialization

# XTTS v2 modelinde gerekli tüm global sınıflar
torch.serialization.add_safe_globals([XttsConfig, XttsAudioConfig, BaseDatasetConfig, XttsArgs])

from TTS.api import TTS

MODEL_NAME = "tts_models/multilingual/multi-dataset/xtts_v2"
tts = TTS(MODEL_NAME)

text = "Tabii. Şu anda 5G Sınırsız planındayım ama bana uygun olup olmadığından emin değilim. 5G Temel planına indirmeyi düşünüyorum, ama iki plan arasındaki farkın ne olduğundan emin değilim."
tts.tts_to_file(
    text=text,
    file_path="output_xtts_2.wav",
    speaker_wav="/content/0003_04_20250729_185406_7d4f3bfe.wav",
    language="tr"
)